#!/usr/bin/perl
use strict;
=pod
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=cut

my $prev = 1;
my $fib = 1;
my $total = 0;
while ($fib < 4000000) {
    $total += $fib if ($fib % 2 == 0);
    my $tmp = $fib;
    $fib = $fib + $prev;
    $prev = $tmp;
}
print $total . "\n";

exit;
